[env:esp32-c3-devkitm-1]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
upload_speed = 921600
build_flags =
  -std=gnu++17
  -DSIMULATE_SENSOR
lib_deps =
  adafruit/Adafruit SHT4x Library
  h2zero/NimBLE-Arduino

